### PR TITLE
Add syntax highlighting to comment format.

### PR DESCRIPTION
**Pull request by tobetchi**
// is inline comment format for Unity shader.

### CODE REVIEW

**Comment by midnightSuyama** [comment]
@tobetchi Thanks. However, I couldn't understand the necessity.
`//` comment sequence is already set.
https://github.com/midnightSuyama/shader-mode/blob/76539359418d3d3cd4d2714a189b1bb777c2c15c/shader-mode.el#L180

**Comment by tobetchi** [comment]
Sorry, That was wrong description.
The description I should have written not Syntax highlighting but Comment out.

**Comment by midnightSuyama** [comment]
@tobetchi I see ! That is, is it for `M-;` ?

**Comment by tobetchi** [comment]
@midnightSuyama yes!

**Comment by midnightSuyama** [comment]
@tobetchi 👍

**Pull request merged**
